#spring:
#  datasource:
#    url: jdbc:oracle:thin:@//localhost:1521/xepdb1
#    username: admin_user
#    password: admin
#    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: oracle
#    database-platform: org.hibernate.dialect.OracleDialect
#
#application:
#  security:
#    jwt:
#      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 5400000
